### ISSUE TITLE
Issues to fix

### ISSUE THREAD

**Issue by aklenik** [bistaastha/caliper#1]
# 1. Non-functional issues
1. Copy-paste error: Minimum -> Maximum
https://github.com/bistaastha/caliper/blob/78dad7370c91626fa613df695a6b27ccc056ffec/packages/caliper-core/lib/worker/workload/declarative/value-providers/uniform-random-value-provider.js#L51-L55
1. No need to wrap simple function calls, `const result = valueProvider.generateValue();` is enough, and then `expect(result)...`. Same goes for other test cases.
https://github.com/bistaastha/caliper/blob/78dad7370c91626fa613df695a6b27ccc056ffec/packages/caliper-core/test/worker/workload/declarative/value-providers/uniform-random-value-provider.test.js#L65-L71
1. Repeating code should be encapsulated in a separate/reusable function
https://github.com/bistaastha/caliper/blob/78dad7370c91626fa613df695a6b27ccc056ffec/packages/caliper-core/test/worker/workload/declarative/value-providers/uniform-random-value-provider.test.js#L69-L74

# 2. Small issues/enhancements
1. Error message should be less technical, e.g., "incorrect variable name"
https://github.com/bistaastha/caliper/blob/78dad7370c91626fa613df695a6b27ccc056ffec/packages/caliper-core/lib/worker/workload/declarative/value-providers/variable-reference-value-provider.js#L33-L40
1. Error message should be more specific, e.g., which variable (and not parameter) name is not found.
https://github.com/bistaastha/caliper/blob/78dad7370c91626fa613df695a6b27ccc056ffec/packages/caliper-core/lib/worker/workload/declarative/value-providers/variable-reference-value-provider.js#L42-L44
1. Error message should be less technical, e.g., "incorrect parameter name"
https://github.com/bistaastha/caliper/blob/78dad7370c91626fa613df695a6b27ccc056ffec/packages/caliper-core/lib/worker/workload/declarative/value-providers/parameter-reference-value-provider.js#L33-L40
1. Error message should be more specific, e.g., which parameter name is not found.
https://github.com/bistaastha/caliper/blob/78dad7370c91626fa613df695a6b27ccc056ffec/packages/caliper-core/lib/worker/workload/declarative/value-providers/parameter-reference-value-provider.js#L42-L44

**Comment by bistaastha** [comment]
Resolved!
